package com.qxf.hiswww.dao;

import com.qxf.hiswww.domain.TClazz;
import com.qxf.hiswww.domain.TClazzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    long countByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int deleteByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int insert(TClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int insertSelective(TClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    TClazz selectOneByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    TClazz selectOneByExampleSelective(@Param("example") TClazzExample example, @Param("selective") TClazz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    List<TClazz> selectByExampleSelective(@Param("example") TClazzExample example, @Param("selective") TClazz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    List<TClazz> selectByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    TClazz selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TClazz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    TClazz selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TClazz record, @Param("example") TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TClazz record, @Param("example") TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TClazz record);
}