package com.qxf.hiswww.dao;

import com.qxf.hiswww.domain.TLoginLog;
import com.qxf.hiswww.domain.TLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    long countByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int deleteByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int insert(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int insertSelective(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    TLoginLog selectOneByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    TLoginLog selectOneByExampleSelective(@Param("example") TLoginLogExample example, @Param("selective") TLoginLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    List<TLoginLog> selectByExampleSelective(@Param("example") TLoginLogExample example, @Param("selective") TLoginLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    List<TLoginLog> selectByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    TLoginLog selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TLoginLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    TLoginLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TLoginLog record, @Param("example") TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TLoginLog record, @Param("example") TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TLoginLog record);
}