package com.qxf.hiswww.domain;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;

public class QuestionFillJudge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.create_id
     *
     * @mbg.generated
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.create_time
     *
     * @mbg.generated
     */
    private LocalDate createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.update_id
     *
     * @mbg.generated
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.update_time
     *
     * @mbg.generated
     */
    private LocalDate updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_content
     *
     * @mbg.generated
     */
    private String questionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_answer
     *
     * @mbg.generated
     */
    private String questionAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_explain
     *
     * @mbg.generated
     */
    private String questionExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_score
     *
     * @mbg.generated
     */
    private String questionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_level
     *
     * @mbg.generated
     */
    private String questionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_subject
     *
     * @mbg.generated
     */
    private String questionSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_fill_judge.question_type
     *
     * @mbg.generated
     */
    private Integer questionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.id
     *
     * @return the value of question_fill_judge.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.id
     *
     * @param id the value for question_fill_judge.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.create_id
     *
     * @return the value of question_fill_judge.create_id
     *
     * @mbg.generated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.create_id
     *
     * @param createId the value for question_fill_judge.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.create_time
     *
     * @return the value of question_fill_judge.create_time
     *
     * @mbg.generated
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.create_time
     *
     * @param createTime the value for question_fill_judge.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.update_id
     *
     * @return the value of question_fill_judge.update_id
     *
     * @mbg.generated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.update_id
     *
     * @param updateId the value for question_fill_judge.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.update_time
     *
     * @return the value of question_fill_judge.update_time
     *
     * @mbg.generated
     */
    public LocalDate getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.update_time
     *
     * @param updateTime the value for question_fill_judge.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDate updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_content
     *
     * @return the value of question_fill_judge.question_content
     *
     * @mbg.generated
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_content
     *
     * @param questionContent the value for question_fill_judge.question_content
     *
     * @mbg.generated
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_answer
     *
     * @return the value of question_fill_judge.question_answer
     *
     * @mbg.generated
     */
    public String getQuestionAnswer() {
        return questionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_answer
     *
     * @param questionAnswer the value for question_fill_judge.question_answer
     *
     * @mbg.generated
     */
    public void setQuestionAnswer(String questionAnswer) {
        this.questionAnswer = questionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_explain
     *
     * @return the value of question_fill_judge.question_explain
     *
     * @mbg.generated
     */
    public String getQuestionExplain() {
        return questionExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_explain
     *
     * @param questionExplain the value for question_fill_judge.question_explain
     *
     * @mbg.generated
     */
    public void setQuestionExplain(String questionExplain) {
        this.questionExplain = questionExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_score
     *
     * @return the value of question_fill_judge.question_score
     *
     * @mbg.generated
     */
    public String getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_score
     *
     * @param questionScore the value for question_fill_judge.question_score
     *
     * @mbg.generated
     */
    public void setQuestionScore(String questionScore) {
        this.questionScore = questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_level
     *
     * @return the value of question_fill_judge.question_level
     *
     * @mbg.generated
     */
    public String getQuestionLevel() {
        return questionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_level
     *
     * @param questionLevel the value for question_fill_judge.question_level
     *
     * @mbg.generated
     */
    public void setQuestionLevel(String questionLevel) {
        this.questionLevel = questionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_subject
     *
     * @return the value of question_fill_judge.question_subject
     *
     * @mbg.generated
     */
    public String getQuestionSubject() {
        return questionSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_subject
     *
     * @param questionSubject the value for question_fill_judge.question_subject
     *
     * @mbg.generated
     */
    public void setQuestionSubject(String questionSubject) {
        this.questionSubject = questionSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_fill_judge.question_type
     *
     * @return the value of question_fill_judge.question_type
     *
     * @mbg.generated
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_fill_judge.question_type
     *
     * @param questionType the value for question_fill_judge.question_type
     *
     * @mbg.generated
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_fill_judge
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createId=").append(createId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateId=").append(updateId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", questionContent=").append(questionContent);
        sb.append(", questionAnswer=").append(questionAnswer);
        sb.append(", questionExplain=").append(questionExplain);
        sb.append(", questionScore=").append(questionScore);
        sb.append(", questionLevel=").append(questionLevel);
        sb.append(", questionSubject=").append(questionSubject);
        sb.append(", questionType=").append(questionType);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_fill_judge
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuestionFillJudge other = (QuestionFillJudge) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getQuestionContent() == null ? other.getQuestionContent() == null : this.getQuestionContent().equals(other.getQuestionContent()))
            && (this.getQuestionAnswer() == null ? other.getQuestionAnswer() == null : this.getQuestionAnswer().equals(other.getQuestionAnswer()))
            && (this.getQuestionExplain() == null ? other.getQuestionExplain() == null : this.getQuestionExplain().equals(other.getQuestionExplain()))
            && (this.getQuestionScore() == null ? other.getQuestionScore() == null : this.getQuestionScore().equals(other.getQuestionScore()))
            && (this.getQuestionLevel() == null ? other.getQuestionLevel() == null : this.getQuestionLevel().equals(other.getQuestionLevel()))
            && (this.getQuestionSubject() == null ? other.getQuestionSubject() == null : this.getQuestionSubject().equals(other.getQuestionSubject()))
            && (this.getQuestionType() == null ? other.getQuestionType() == null : this.getQuestionType().equals(other.getQuestionType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_fill_judge
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getQuestionContent() == null) ? 0 : getQuestionContent().hashCode());
        result = prime * result + ((getQuestionAnswer() == null) ? 0 : getQuestionAnswer().hashCode());
        result = prime * result + ((getQuestionExplain() == null) ? 0 : getQuestionExplain().hashCode());
        result = prime * result + ((getQuestionScore() == null) ? 0 : getQuestionScore().hashCode());
        result = prime * result + ((getQuestionLevel() == null) ? 0 : getQuestionLevel().hashCode());
        result = prime * result + ((getQuestionSubject() == null) ? 0 : getQuestionSubject().hashCode());
        result = prime * result + ((getQuestionType() == null) ? 0 : getQuestionType().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table question_fill_judge
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        createId("create_id", "createId", "VARCHAR", false),
        createTime("create_time", "createTime", "DATE", false),
        updateId("update_id", "updateId", "VARCHAR", false),
        updateTime("update_time", "updateTime", "DATE", false),
        questionContent("question_content", "questionContent", "VARCHAR", false),
        questionAnswer("question_answer", "questionAnswer", "VARCHAR", false),
        questionExplain("question_explain", "questionExplain", "VARCHAR", false),
        questionScore("question_score", "questionScore", "VARCHAR", false),
        questionLevel("question_level", "questionLevel", "VARCHAR", false),
        questionSubject("question_subject", "questionSubject", "VARCHAR", false),
        questionType("question_type", "questionType", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_fill_judge
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}