package com.qxf.hiswww.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class TCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.students_post
     *
     * @mbg.generated
     */
    private String studentsPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.out_supervisor
     *
     * @mbg.generated
     */
    private String outSupervisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.supervisor_post
     *
     * @mbg.generated
     */
    private String supervisorPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.outor_phone
     *
     * @mbg.generated
     */
    private String outorPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.studnet_id
     *
     * @mbg.generated
     */
    private String studnetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.c_describe
     *
     * @mbg.generated
     */
    private String cDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.id
     *
     * @return the value of t_company.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.id
     *
     * @param id the value for t_company.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_name
     *
     * @return the value of t_company.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_name
     *
     * @param companyName the value for t_company.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.students_post
     *
     * @return the value of t_company.students_post
     *
     * @mbg.generated
     */
    public String getStudentsPost() {
        return studentsPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.students_post
     *
     * @param studentsPost the value for t_company.students_post
     *
     * @mbg.generated
     */
    public void setStudentsPost(String studentsPost) {
        this.studentsPost = studentsPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.out_supervisor
     *
     * @return the value of t_company.out_supervisor
     *
     * @mbg.generated
     */
    public String getOutSupervisor() {
        return outSupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.out_supervisor
     *
     * @param outSupervisor the value for t_company.out_supervisor
     *
     * @mbg.generated
     */
    public void setOutSupervisor(String outSupervisor) {
        this.outSupervisor = outSupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.supervisor_post
     *
     * @return the value of t_company.supervisor_post
     *
     * @mbg.generated
     */
    public String getSupervisorPost() {
        return supervisorPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.supervisor_post
     *
     * @param supervisorPost the value for t_company.supervisor_post
     *
     * @mbg.generated
     */
    public void setSupervisorPost(String supervisorPost) {
        this.supervisorPost = supervisorPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.outor_phone
     *
     * @return the value of t_company.outor_phone
     *
     * @mbg.generated
     */
    public String getOutorPhone() {
        return outorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.outor_phone
     *
     * @param outorPhone the value for t_company.outor_phone
     *
     * @mbg.generated
     */
    public void setOutorPhone(String outorPhone) {
        this.outorPhone = outorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.studnet_id
     *
     * @return the value of t_company.studnet_id
     *
     * @mbg.generated
     */
    public String getStudnetId() {
        return studnetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.studnet_id
     *
     * @param studnetId the value for t_company.studnet_id
     *
     * @mbg.generated
     */
    public void setStudnetId(String studnetId) {
        this.studnetId = studnetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.course_id
     *
     * @return the value of t_company.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.course_id
     *
     * @param courseId the value for t_company.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.c_describe
     *
     * @return the value of t_company.c_describe
     *
     * @mbg.generated
     */
    public String getcDescribe() {
        return cDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.c_describe
     *
     * @param cDescribe the value for t_company.c_describe
     *
     * @mbg.generated
     */
    public void setcDescribe(String cDescribe) {
        this.cDescribe = cDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyName=").append(companyName);
        sb.append(", studentsPost=").append(studentsPost);
        sb.append(", outSupervisor=").append(outSupervisor);
        sb.append(", supervisorPost=").append(supervisorPost);
        sb.append(", outorPhone=").append(outorPhone);
        sb.append(", studnetId=").append(studnetId);
        sb.append(", courseId=").append(courseId);
        sb.append(", cDescribe=").append(cDescribe);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCompany other = (TCompany) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getStudentsPost() == null ? other.getStudentsPost() == null : this.getStudentsPost().equals(other.getStudentsPost()))
            && (this.getOutSupervisor() == null ? other.getOutSupervisor() == null : this.getOutSupervisor().equals(other.getOutSupervisor()))
            && (this.getSupervisorPost() == null ? other.getSupervisorPost() == null : this.getSupervisorPost().equals(other.getSupervisorPost()))
            && (this.getOutorPhone() == null ? other.getOutorPhone() == null : this.getOutorPhone().equals(other.getOutorPhone()))
            && (this.getStudnetId() == null ? other.getStudnetId() == null : this.getStudnetId().equals(other.getStudnetId()))
            && (this.getCourseId() == null ? other.getCourseId() == null : this.getCourseId().equals(other.getCourseId()))
            && (this.getcDescribe() == null ? other.getcDescribe() == null : this.getcDescribe().equals(other.getcDescribe()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getStudentsPost() == null) ? 0 : getStudentsPost().hashCode());
        result = prime * result + ((getOutSupervisor() == null) ? 0 : getOutSupervisor().hashCode());
        result = prime * result + ((getSupervisorPost() == null) ? 0 : getSupervisorPost().hashCode());
        result = prime * result + ((getOutorPhone() == null) ? 0 : getOutorPhone().hashCode());
        result = prime * result + ((getStudnetId() == null) ? 0 : getStudnetId().hashCode());
        result = prime * result + ((getCourseId() == null) ? 0 : getCourseId().hashCode());
        result = prime * result + ((getcDescribe() == null) ? 0 : getcDescribe().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        companyName("company_name", "companyName", "VARCHAR", false),
        studentsPost("students_post", "studentsPost", "VARCHAR", false),
        outSupervisor("out_supervisor", "outSupervisor", "VARCHAR", false),
        supervisorPost("supervisor_post", "supervisorPost", "VARCHAR", false),
        outorPhone("outor_phone", "outorPhone", "VARCHAR", false),
        studnetId("studnet_id", "studnetId", "VARCHAR", false),
        courseId("course_id", "courseId", "VARCHAR", false),
        cDescribe("c_describe", "cDescribe", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}