package com.qxf.hiswww.domain;

import java.util.ArrayList;
import java.util.List;

public class TCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public TCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public TCompanyExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public TCompanyExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        TCompanyExample example = new TCompanyExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public TCompanyExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public TCompanyExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCompanyNameEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("company_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCompanyNameNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("company_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCompanyNameGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("company_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCompanyNameGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("company_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCompanyNameLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("company_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCompanyNameLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("company_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andStudentsPostIsNull() {
            addCriterion("students_post is null");
            return (Criteria) this;
        }

        public Criteria andStudentsPostIsNotNull() {
            addCriterion("students_post is not null");
            return (Criteria) this;
        }

        public Criteria andStudentsPostEqualTo(String value) {
            addCriterion("students_post =", value, "studentsPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudentsPostEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("students_post = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudentsPostNotEqualTo(String value) {
            addCriterion("students_post <>", value, "studentsPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudentsPostNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("students_post <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudentsPostGreaterThan(String value) {
            addCriterion("students_post >", value, "studentsPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudentsPostGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("students_post > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudentsPostGreaterThanOrEqualTo(String value) {
            addCriterion("students_post >=", value, "studentsPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudentsPostGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("students_post >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudentsPostLessThan(String value) {
            addCriterion("students_post <", value, "studentsPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudentsPostLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("students_post < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudentsPostLessThanOrEqualTo(String value) {
            addCriterion("students_post <=", value, "studentsPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudentsPostLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("students_post <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudentsPostLike(String value) {
            addCriterion("students_post like", value, "studentsPost");
            return (Criteria) this;
        }

        public Criteria andStudentsPostNotLike(String value) {
            addCriterion("students_post not like", value, "studentsPost");
            return (Criteria) this;
        }

        public Criteria andStudentsPostIn(List<String> values) {
            addCriterion("students_post in", values, "studentsPost");
            return (Criteria) this;
        }

        public Criteria andStudentsPostNotIn(List<String> values) {
            addCriterion("students_post not in", values, "studentsPost");
            return (Criteria) this;
        }

        public Criteria andStudentsPostBetween(String value1, String value2) {
            addCriterion("students_post between", value1, value2, "studentsPost");
            return (Criteria) this;
        }

        public Criteria andStudentsPostNotBetween(String value1, String value2) {
            addCriterion("students_post not between", value1, value2, "studentsPost");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorIsNull() {
            addCriterion("out_supervisor is null");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorIsNotNull() {
            addCriterion("out_supervisor is not null");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorEqualTo(String value) {
            addCriterion("out_supervisor =", value, "outSupervisor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutSupervisorEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("out_supervisor = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutSupervisorNotEqualTo(String value) {
            addCriterion("out_supervisor <>", value, "outSupervisor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutSupervisorNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("out_supervisor <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutSupervisorGreaterThan(String value) {
            addCriterion("out_supervisor >", value, "outSupervisor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutSupervisorGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("out_supervisor > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutSupervisorGreaterThanOrEqualTo(String value) {
            addCriterion("out_supervisor >=", value, "outSupervisor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutSupervisorGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("out_supervisor >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutSupervisorLessThan(String value) {
            addCriterion("out_supervisor <", value, "outSupervisor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutSupervisorLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("out_supervisor < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutSupervisorLessThanOrEqualTo(String value) {
            addCriterion("out_supervisor <=", value, "outSupervisor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutSupervisorLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("out_supervisor <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutSupervisorLike(String value) {
            addCriterion("out_supervisor like", value, "outSupervisor");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorNotLike(String value) {
            addCriterion("out_supervisor not like", value, "outSupervisor");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorIn(List<String> values) {
            addCriterion("out_supervisor in", values, "outSupervisor");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorNotIn(List<String> values) {
            addCriterion("out_supervisor not in", values, "outSupervisor");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorBetween(String value1, String value2) {
            addCriterion("out_supervisor between", value1, value2, "outSupervisor");
            return (Criteria) this;
        }

        public Criteria andOutSupervisorNotBetween(String value1, String value2) {
            addCriterion("out_supervisor not between", value1, value2, "outSupervisor");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostIsNull() {
            addCriterion("supervisor_post is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostIsNotNull() {
            addCriterion("supervisor_post is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostEqualTo(String value) {
            addCriterion("supervisor_post =", value, "supervisorPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andSupervisorPostEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("supervisor_post = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSupervisorPostNotEqualTo(String value) {
            addCriterion("supervisor_post <>", value, "supervisorPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andSupervisorPostNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("supervisor_post <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSupervisorPostGreaterThan(String value) {
            addCriterion("supervisor_post >", value, "supervisorPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andSupervisorPostGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("supervisor_post > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSupervisorPostGreaterThanOrEqualTo(String value) {
            addCriterion("supervisor_post >=", value, "supervisorPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andSupervisorPostGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("supervisor_post >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSupervisorPostLessThan(String value) {
            addCriterion("supervisor_post <", value, "supervisorPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andSupervisorPostLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("supervisor_post < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSupervisorPostLessThanOrEqualTo(String value) {
            addCriterion("supervisor_post <=", value, "supervisorPost");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andSupervisorPostLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("supervisor_post <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSupervisorPostLike(String value) {
            addCriterion("supervisor_post like", value, "supervisorPost");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostNotLike(String value) {
            addCriterion("supervisor_post not like", value, "supervisorPost");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostIn(List<String> values) {
            addCriterion("supervisor_post in", values, "supervisorPost");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostNotIn(List<String> values) {
            addCriterion("supervisor_post not in", values, "supervisorPost");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostBetween(String value1, String value2) {
            addCriterion("supervisor_post between", value1, value2, "supervisorPost");
            return (Criteria) this;
        }

        public Criteria andSupervisorPostNotBetween(String value1, String value2) {
            addCriterion("supervisor_post not between", value1, value2, "supervisorPost");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneIsNull() {
            addCriterion("outor_phone is null");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneIsNotNull() {
            addCriterion("outor_phone is not null");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneEqualTo(String value) {
            addCriterion("outor_phone =", value, "outorPhone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutorPhoneEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("outor_phone = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutorPhoneNotEqualTo(String value) {
            addCriterion("outor_phone <>", value, "outorPhone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutorPhoneNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("outor_phone <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutorPhoneGreaterThan(String value) {
            addCriterion("outor_phone >", value, "outorPhone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutorPhoneGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("outor_phone > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutorPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("outor_phone >=", value, "outorPhone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutorPhoneGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("outor_phone >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutorPhoneLessThan(String value) {
            addCriterion("outor_phone <", value, "outorPhone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutorPhoneLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("outor_phone < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutorPhoneLessThanOrEqualTo(String value) {
            addCriterion("outor_phone <=", value, "outorPhone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andOutorPhoneLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("outor_phone <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOutorPhoneLike(String value) {
            addCriterion("outor_phone like", value, "outorPhone");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneNotLike(String value) {
            addCriterion("outor_phone not like", value, "outorPhone");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneIn(List<String> values) {
            addCriterion("outor_phone in", values, "outorPhone");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneNotIn(List<String> values) {
            addCriterion("outor_phone not in", values, "outorPhone");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneBetween(String value1, String value2) {
            addCriterion("outor_phone between", value1, value2, "outorPhone");
            return (Criteria) this;
        }

        public Criteria andOutorPhoneNotBetween(String value1, String value2) {
            addCriterion("outor_phone not between", value1, value2, "outorPhone");
            return (Criteria) this;
        }

        public Criteria andStudnetIdIsNull() {
            addCriterion("studnet_id is null");
            return (Criteria) this;
        }

        public Criteria andStudnetIdIsNotNull() {
            addCriterion("studnet_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudnetIdEqualTo(String value) {
            addCriterion("studnet_id =", value, "studnetId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudnetIdEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("studnet_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudnetIdNotEqualTo(String value) {
            addCriterion("studnet_id <>", value, "studnetId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudnetIdNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("studnet_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudnetIdGreaterThan(String value) {
            addCriterion("studnet_id >", value, "studnetId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudnetIdGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("studnet_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudnetIdGreaterThanOrEqualTo(String value) {
            addCriterion("studnet_id >=", value, "studnetId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudnetIdGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("studnet_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudnetIdLessThan(String value) {
            addCriterion("studnet_id <", value, "studnetId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudnetIdLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("studnet_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudnetIdLessThanOrEqualTo(String value) {
            addCriterion("studnet_id <=", value, "studnetId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andStudnetIdLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("studnet_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStudnetIdLike(String value) {
            addCriterion("studnet_id like", value, "studnetId");
            return (Criteria) this;
        }

        public Criteria andStudnetIdNotLike(String value) {
            addCriterion("studnet_id not like", value, "studnetId");
            return (Criteria) this;
        }

        public Criteria andStudnetIdIn(List<String> values) {
            addCriterion("studnet_id in", values, "studnetId");
            return (Criteria) this;
        }

        public Criteria andStudnetIdNotIn(List<String> values) {
            addCriterion("studnet_id not in", values, "studnetId");
            return (Criteria) this;
        }

        public Criteria andStudnetIdBetween(String value1, String value2) {
            addCriterion("studnet_id between", value1, value2, "studnetId");
            return (Criteria) this;
        }

        public Criteria andStudnetIdNotBetween(String value1, String value2) {
            addCriterion("studnet_id not between", value1, value2, "studnetId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(String value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCourseIdEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("course_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(String value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCourseIdNotEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("course_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(String value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCourseIdGreaterThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("course_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(String value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCourseIdGreaterThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("course_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(String value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCourseIdLessThanColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("course_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(String value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria andCourseIdLessThanOrEqualToColumn(TCompany.Column column) {
            addCriterion(new StringBuilder("course_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCourseIdLike(String value) {
            addCriterion("course_id like", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotLike(String value) {
            addCriterion("course_id not like", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<String> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<String> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(String value1, String value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(String value1, String value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_company
         *
         * @mbg.generated
         */
        private TCompanyExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        protected Criteria(TCompanyExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public TCompanyExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table t_company
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_company
         *
         * @mbg.generated
         */
        void example(com.qxf.hiswww.domain.TCompanyExample example);
    }
}